name: openfold-env
channels:
  - pytorch
  - conda-forge
  - nvidia
  - bioconda
dependencies:
  - python=3.10
  - setuptools=59.5.0
  - pip
  - openmm=7.7
  - pdbfixer
  - pytorch-lightning
  - biopython
  - numpy<2.0
  - pandas
  - PyYAML==5.4.1
  - requests
  - scipy
  - tqdm==4.62.2
  - typing-extensions==4.0
  - wandb
  - modelcif==0.7
  - awscli
  - ml-collections
  - aria2
  - mkl<2024.0
  - git
  - bioconda::hmmer==3.3.2
  - bioconda::hhsuite==3.3.0
  - bioconda::kalign2==2.04
  - bioconda::mmseqs2
  - pytorch=2.0.*=*cuda118*
  - pytorch-cuda=11.8
  - cuda-nvcc=11.8
  - cuda-libraries-dev=11.8
  - deepspeed=0.12.*=*cuda118*
  - dm-tree=0.1
  # documentation
  - sphinx
  - sphinxcontrib-bibtex
  - furo
  - myst-parser=3
  - pip:
      - git+https://github.com/NVIDIA/dllogger.git
      - https://github.com/Dao-AILab/flash-attention/releases/download/v2.2.5/flash_attn-2.2.5+cu118torch2.0cxx11abiFALSE-cp310-cp310-linux_x86_64.whl
